In [129]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [130]:
df = pd.read_csv("Sleep_health_and_lifestyle_dataset.csv")

In [131]:
df.head()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

In [132]:
df.tail()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

In [133]:
df.columns

Index(['Person ID', 'Gender', 'Age', 'Occupation', 'Sleep Duration',
       'Quality of Sleep', 'Physical Activity Level', 'Stress Level',
       'BMI Category', 'Blood Pressure', 'Heart Rate', 'Daily Steps',
       'Sleep Disorder'],
      dtype='object')

In [134]:
df.shape

(374, 13)

In [135]:
df.dtypes

Person ID                    int64
Gender                      object
Age                          int64
Occupation                  object
Sleep Duration             float64
Quality of Sleep             int64
Physical Activity Level      int64
Stress Level                 int64
BMI Category                object
Blood Pressure              object
Heart Rate                   int64
Daily Steps                  int64
Sleep Disorder              object
dtype: object

In [136]:
df.describe()

,Person ID,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps
count,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000
mean,187.500000,42.184492,7.132086,7.312834,59.171123,5.385027,70.165775,6816.844920
std,108.108742,8.673133,0.795657,1.196956,20.830804,1.774526,4.135676,1617.915679
min,1.000000,27.000000,5.800000,4.000000,30.000000,3.000000,65.000000,3000.000000
25%,94.250000,35.250000,6.400000,6.000000,45.000000,4.000000,68.000000,5600.000000
50%,187.500000,43.000000,7.200000,7.000000,60.000000,5.000000,70.000000,7000.000000
75%,280.750000,50.000000,7.800000,8.000000,75.000000,7.000000,72.000000,8000.000000
max,374.000000,59.000000,8.500000,9.000000,90.000000,8.000000,86.000000,10000.000000

In [137]:
df.isnull().sum()

Person ID                    0
Gender                       0
Age                          0
Occupation                   0
Sleep Duration               0
Quality of Sleep             0
Physical Activity Level      0
Stress Level                 0
BMI Category                 0
Blood Pressure               0
Heart Rate                   0
Daily Steps                  0
Sleep Disorder             219
dtype: int64

In [138]:
df.fillna(0,inplace = True)

In [139]:
df.isnull().sum()

Person ID                  0
Gender                     0
Age                        0
Occupation                 0
Sleep Duration             0
Quality of Sleep           0
Physical Activity Level    0
Stress Level               0
BMI Category               0
Blood Pressure             0
Heart Rate                 0
Daily Steps                0
Sleep Disorder             0
dtype: int64

## Hot Encoding the Object datatypes GENDER, BMI CATEGORY

In [140]:
Gender_code = pd.get_dummies(df.Gender,dtype=int)
Gender_code.head(3)

   Female  Male
0       0     1
1       0     1
2       0     1

In [141]:
BMI_code = pd.get_dummies(df['BMI Category'] ,dtype=int)
BMI_code.head(3)

   Normal  Normal Weight  Obese  Overweight
0       0              0      0           1
1       1              0      0           0
2       1              0      0           0

In [142]:
df['BMI Category'].unique()

array(['Overweight', 'Normal', 'Obese', 'Normal Weight'], dtype=object)

In [143]:
df['BMI Category'] = df['BMI Category'].replace({'Normal Weight': 'Normal'})

In [144]:
df['BMI Category'].unique()

array(['Overweight', 'Normal', 'Obese'], dtype=object)

In [145]:
BMI_code = pd.get_dummies(df['BMI Category'] ,dtype=int)
BMI_code.head(3)

   Normal  Obese  Overweight
0       0      0           1
1       1      0           0
2       1      0           0

In [146]:
df.head(2)

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,0
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,0

In [147]:
df2 = pd.concat([df,Gender_code],axis='columns')
df2.head(3)

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder,Female,Male
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,0,0,1
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,0,0,1
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,0,0,1

In [148]:
df3 = pd.concat([df2,BMI_code],axis='columns')
df3.head(3)

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder,Female,Male,Normal,Obese,Overweight
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,0,0,1,0,0,1
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,0,0,1,1,0,0
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,0,0,1,1,0,0

In [149]:
df4 = df3.drop(['Gender','BMI Category', 'Occupation','Person ID'],axis='columns')
df4.head(3)

,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder,Female,Male,Normal,Obese,Overweight
0,27,6.1,6,42,6,126/83,77,4200,0,0,1,0,0,1
1,28,6.2,6,60,8,125/80,75,10000,0,0,1,1,0,0
2,28,6.2,6,60,8,125/80,75,10000,0,0,1,1,0,0

In [150]:
df4[['Systolic', 'Diastolic']] = df4['Blood Pressure'].str.split('/', expand=True)
df4[['Systolic', 'Diastolic']] = df4[['Systolic', 'Diastolic']].apply(pd.to_numeric)
df4.head()

,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder,Female,Male,Normal,Obese,Overweight,Systolic,Diastolic
0,27,6.1,6,42,6,126/83,77,4200,0,0,1,0,0,1,126,83
1,28,6.2,6,60,8,125/80,75,10000,0,0,1,1,0,0,125,80
2,28,6.2,6,60,8,125/80,75,10000,0,0,1,1,0,0,125,80
3,28,5.9,4,30,8,140/90,85,3000,Sleep Apnea,0,1,0,1,0,140,90
4,28,5.9,4,30,8,140/90,85,3000,Sleep Apnea,0,1,0,1,0,140,90

In [151]:
df5 = df4.drop('Blood Pressure',axis = 'columns')
df5.head()

,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps,Sleep Disorder,Female,Male,Normal,Obese,Overweight,Systolic,Diastolic
0,27,6.1,6,42,6,77,4200,0,0,1,0,0,1,126,83
1,28,6.2,6,60,8,75,10000,0,0,1,1,0,0,125,80
2,28,6.2,6,60,8,75,10000,0,0,1,1,0,0,125,80
3,28,5.9,4,30,8,85,3000,Sleep Apnea,0,1,0,1,0,140,90
4,28,5.9,4,30,8,85,3000,Sleep Apnea,0,1,0,1,0,140,90

In [154]:
import pandas as pd
from sklearn.model_selection import GridSearchCV, ShuffleSplit
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [155]:
df5["Sleep Disorder_numeric"] = df["Sleep Disorder"].map({0:0,'Sleep Apnea':1, 'Insomnia':2})

In [156]:
df5['Sleep Disorder_numeric'].unique()

array([0, 1, 2], dtype=int64)

In [157]:
df5.head(2)

,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps,Sleep Disorder,Female,Male,Normal,Obese,Overweight,Systolic,Diastolic,Sleep Disorder_numeric
0,27,6.1,6,42,6,77,4200,0,0,1,0,0,1,126,83,0
1,28,6.2,6,60,8,75,10000,0,0,1,1,0,0,125,80,0

In [158]:
df6 = df5.drop(['Sleep Disorder'], axis=1)
df6.head(3)

,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps,Female,Male,Normal,Obese,Overweight,Systolic,Diastolic,Sleep Disorder_numeric
0,27,6.1,6,42,6,77,4200,0,1,0,0,1,126,83,0
1,28,6.2,6,60,8,75,10000,0,1,1,0,0,125,80,0
2,28,6.2,6,60,8,75,10000,0,1,1,0,0,125,80,0

In [159]:
df6.to_excel("new_df.xlsx",index=False)

In [160]:
print(y.shape)
print(X.shape)

(374,)
(374, 14)

In [161]:
X.head()

,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps,Female,Male,Normal,Obese,Overweight,Systolic,Diastolic
0,-1.753096,-1.298887,-1.098280,-0.825418,0.347021,1.654719,-1.619584,0,1,0,0,1,-0.330002,-0.268102
1,-1.637643,-1.173036,-1.098280,0.039844,1.475592,1.170474,1.970077,0,1,1,0,0,-0.459239,-0.755640
2,-1.637643,-1.173036,-1.098280,0.039844,1.475592,1.170474,1.970077,0,1,1,0,0,-0.459239,-0.755640
3,-1.637643,-1.550588,-2.771424,-1.402260,1.475592,3.591698,-2.362273,0,1,0,1,0,1.479309,0.869486
4,-1.637643,-1.550588,-2.771424,-1.402260,1.475592,3.591698,-2.362273,0,1,0,1,0,1.479309,0.869486

In [162]:
scaler_standard = StandardScaler()

In [163]:
df6['Age'] = scaler_standard.fit_transform(df[['Age']])
df6.head(2)

,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps,Female,Male,Normal,Obese,Overweight,Systolic,Diastolic,Sleep Disorder_numeric
0,-1.753096,6.1,6,42,6,77,4200,0,1,0,0,1,126,83,0
1,-1.637643,6.2,6,60,8,75,10000,0,1,1,0,0,125,80,0

In [164]:
y.head()

0    0
1    0
2    0
3    1
4    1
Name: Sleep Disorder_numeric, dtype: int64

In [165]:
df6['Sleep Duration'] = scaler_standard.fit_transform(df[['Sleep Duration']])
df6.head(2)

,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps,Female,Male,Normal,Obese,Overweight,Systolic,Diastolic,Sleep Disorder_numeric
0,-1.753096,-1.298887,6,42,6,77,4200,0,1,0,0,1,126,83,0
1,-1.637643,-1.173036,6,60,8,75,10000,0,1,1,0,0,125,80,0

In [166]:
df6['Quality of Sleep'] = scaler_standard.fit_transform(df[['Quality of Sleep']])
df6.head(2)

,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps,Female,Male,Normal,Obese,Overweight,Systolic,Diastolic,Sleep Disorder_numeric
0,-1.753096,-1.298887,-1.09828,42,6,77,4200,0,1,0,0,1,126,83,0
1,-1.637643,-1.173036,-1.09828,60,8,75,10000,0,1,1,0,0,125,80,0

In [167]:
df6['Physical Activity Level'] = scaler_standard.fit_transform(df[['Physical Activity Level']])
df6.head(2)

,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps,Female,Male,Normal,Obese,Overweight,Systolic,Diastolic,Sleep Disorder_numeric
0,-1.753096,-1.298887,-1.09828,-0.825418,6,77,4200,0,1,0,0,1,126,83,0
1,-1.637643,-1.173036,-1.09828,0.039844,8,75,10000,0,1,1,0,0,125,80,0

In [168]:
df6['Stress Level'] = scaler_standard.fit_transform(df[['Stress Level']])
df6.head(2)

,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps,Female,Male,Normal,Obese,Overweight,Systolic,Diastolic,Sleep Disorder_numeric
0,-1.753096,-1.298887,-1.09828,-0.825418,0.347021,77,4200,0,1,0,0,1,126,83,0
1,-1.637643,-1.173036,-1.09828,0.039844,1.475592,75,10000,0,1,1,0,0,125,80,0

In [169]:
df6['Heart Rate'] = scaler_standard.fit_transform(df[['Heart Rate']])
df6.head(2)

,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps,Female,Male,Normal,Obese,Overweight,Systolic,Diastolic,Sleep Disorder_numeric
0,-1.753096,-1.298887,-1.09828,-0.825418,0.347021,1.654719,4200,0,1,0,0,1,126,83,0
1,-1.637643,-1.173036,-1.09828,0.039844,1.475592,1.170474,10000,0,1,1,0,0,125,80,0

In [170]:
df6['Daily Steps'] = scaler_standard.fit_transform(df[['Daily Steps']])
df6.head(2)

,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps,Female,Male,Normal,Obese,Overweight,Systolic,Diastolic,Sleep Disorder_numeric
0,-1.753096,-1.298887,-1.09828,-0.825418,0.347021,1.654719,-1.619584,0,1,0,0,1,126,83,0
1,-1.637643,-1.173036,-1.09828,0.039844,1.475592,1.170474,1.970077,0,1,1,0,0,125,80,0

In [171]:
df6['Systolic'] = scaler_standard.fit_transform(df6[['Systolic']])
df6.head(2)

,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps,Female,Male,Normal,Obese,Overweight,Systolic,Diastolic,Sleep Disorder_numeric
0,-1.753096,-1.298887,-1.09828,-0.825418,0.347021,1.654719,-1.619584,0,1,0,0,1,-0.330002,83,0
1,-1.637643,-1.173036,-1.09828,0.039844,1.475592,1.170474,1.970077,0,1,1,0,0,-0.459239,80,0

In [172]:
df6['Diastolic'] = scaler_standard.fit_transform(df6[['Diastolic']])
df6.head(2)

,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps,Female,Male,Normal,Obese,Overweight,Systolic,Diastolic,Sleep Disorder_numeric
0,-1.753096,-1.298887,-1.09828,-0.825418,0.347021,1.654719,-1.619584,0,1,0,0,1,-0.330002,-0.268102,0
1,-1.637643,-1.173036,-1.09828,0.039844,1.475592,1.170474,1.970077,0,1,1,0,0,-0.459239,-0.755640,0

In [173]:
X = df6.drop(['Sleep Disorder_numeric'], axis=1)
y = df6['Sleep Disorder_numeric']

In [174]:
X

,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps,Female,Male,Normal,Obese,Overweight,Systolic,Diastolic
0,-1.753096,-1.298887,-1.098280,-0.825418,0.347021,1.654719,-1.619584,0,1,0,0,1,-0.330002,-0.268102
1,-1.637643,-1.173036,-1.098280,0.039844,1.475592,1.170474,1.970077,0,1,1,0,0,-0.459239,-0.755640
2,-1.637643,-1.173036,-1.098280,0.039844,1.475592,1.170474,1.970077,0,1,1,0,0,-0.459239,-0.755640
3,-1.637643,-1.550588,-2.771424,-1.402260,1.475592,3.591698,-2.362273,0,1,0,1,0,1.479309,0.869486
4,-1.637643,-1.550588,-2.771424,-1.402260,1.475592,3.591698,-2.362273,0,1,0,1,0,1.479309,0.869486
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,1.941401,1.218127,1.411435,0.760896,-1.345836,-0.524383,0.113356,1,0,0,0,1,1.479309,1.682049
370,1.941401,1.092276,1.411435,0.760896,-1.345836,-0.524383,0.113356,1,0,0,0,1,1.479309,1.682049
371,1.941401,1.218127,1.411435,0.760896,-1.345836,-0.524383,0.113356,1,0,0,0,1,1.479309,1.682049
372,1.941401,1.218127,1.411435,0.760896,-1.345836,-0.524383,0.113356,1,0,0,0,1,1.479309,1.682049
373,1.941401,1.218127,1.411435,0.760896,-1.345836,-0.524383,0.113356,1,0,0,0,1,1.479309,1.682049

In [175]:
y.unique()

array([0, 1, 2], dtype=int64)

In [176]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [206]:
# Random Forest Classifier
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)
print(rf.score(X_test,y_test))
# Make predictions
y_pred = rf.predict(X_test)

# Evaluate the model
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.8938053097345132
              precision    recall  f1-score   support

           0       0.94      0.98      0.96        62
           1       0.91      0.74      0.82        27
           2       0.77      0.83      0.80        24

    accuracy                           0.89       113
   macro avg       0.87      0.85      0.86       113
weighted avg       0.90      0.89      0.89       113

[[61  0  1]
 [ 2 20  5]
 [ 2  2 20]]

In [178]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Initialize KNN Classifier
knn = KNeighborsClassifier(n_neighbors=5)  # You can adjust n_neighbors as needed

# Train the model
knn.fit(X_train, y_train)

# Make predictions
y_pred = knn.predict(X_test)

# Evaluate the model
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.98      0.95        62
           1       0.95      0.70      0.81        27
           2       0.78      0.88      0.82        24

    accuracy                           0.89       113
   macro avg       0.88      0.85      0.86       113
weighted avg       0.90      0.89      0.89       113

[[61  0  1]
 [ 3 19  5]
 [ 2  1 21]]

In [179]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

# Initialize SVM Classifier
svm = SVC(kernel='rbf', C=1.0, random_state=42)  # You can change kernel to 'linear', 'poly', etc.

# Train the model
svm.fit(X_train, y_train)

# Make predictions
y_pred = svm.predict(X_test)

# Evaluate the model
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.94      0.98      0.96        62
           1       0.91      0.74      0.82        27
           2       0.77      0.83      0.80        24

    accuracy                           0.89       113
   macro avg       0.87      0.85      0.86       113
weighted avg       0.90      0.89      0.89       113

[[61  0  1]
 [ 2 20  5]
 [ 2  2 20]]

In [180]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Initialize Decision Tree Classifier
dt = DecisionTreeClassifier(criterion='gini', splitter='best', random_state=42)  
# You can change criterion to 'entropy' and splitter to 'random' if needed

# Train the model
dt.fit(X_train, y_train)

# Make predictions
y_pred = dt.predict(X_test)

# Evaluate the model
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.91      0.98      0.95        62
           1       0.90      0.70      0.79        27
           2       0.80      0.83      0.82        24

    accuracy                           0.88       113
   macro avg       0.87      0.84      0.85       113
weighted avg       0.89      0.88      0.88       113

[[61  0  1]
 [ 4 19  4]
 [ 2  2 20]]

In [199]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Initialize MLP Classifier (ANN)
ann = MLPClassifier(hidden_layer_sizes=(100,), activation='relu', solver='adam', max_iter=500, random_state=42)  
# You can change hidden_layer_sizes, activation, solver, etc.

# Train the model
ann.fit(X_train, y_train)

# Make predictions
y_pred = ann.predict(X_test)

# Evaluate the model
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.94      0.98      0.96        62
           1       0.92      0.81      0.86        27
           2       0.83      0.83      0.83        24

    accuracy                           0.91       113
   macro avg       0.90      0.88      0.89       113
weighted avg       0.91      0.91      0.91       113

[[61  0  1]
 [ 2 22  3]
 [ 2  2 20]]

In [200]:
df6.tail(10)

,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps,Female,Male,Normal,Obese,Overweight,Systolic,Diastolic,Sleep Disorder_numeric
364,1.941401,1.092276,1.411435,0.760896,-1.345836,-0.524383,0.113356,1,0,0,0,1,1.479309,1.682049,1
365,1.941401,1.092276,1.411435,0.760896,-1.345836,-0.524383,0.113356,1,0,0,0,1,1.479309,1.682049,1
366,1.941401,1.218127,1.411435,0.760896,-1.345836,-0.524383,0.113356,1,0,0,0,1,1.479309,1.682049,1
367,1.941401,1.092276,1.411435,0.760896,-1.345836,-0.524383,0.113356,1,0,0,0,1,1.479309,1.682049,1
368,1.941401,1.218127,1.411435,0.760896,-1.345836,-0.524383,0.113356,1,0,0,0,1,1.479309,1.682049,1
369,1.941401,1.218127,1.411435,0.760896,-1.345836,-0.524383,0.113356,1,0,0,0,1,1.479309,1.682049,1
370,1.941401,1.092276,1.411435,0.760896,-1.345836,-0.524383,0.113356,1,0,0,0,1,1.479309,1.682049,1
371,1.941401,1.218127,1.411435,0.760896,-1.345836,-0.524383,0.113356,1,0,0,0,1,1.479309,1.682049,1
372,1.941401,1.218127,1.411435,0.760896,-1.345836,-0.524383,0.113356,1,0,0,0,1,1.479309,1.682049,1
373,1.941401,1.218127,1.411435,0.760896,-1.345836,-0.524383,0.113356,1,0,0,0,1,1.479309,1.682049,1

In [201]:
X.columns

Index(['Age', 'Sleep Duration', 'Quality of Sleep', 'Physical Activity Level',
       'Stress Level', 'Heart Rate', 'Daily Steps', 'Female', 'Male', 'Normal',
       'Obese', 'Overweight', 'Systolic', 'Diastolic'],
      dtype='object')

In [227]:
def predict_disorder(Gender, Age, Occupation, Sleep_Duration, Quality_of_Sleep, 
                     Physical_Activity_Level, Stress_Level, BMI_Category, 
                     Blood_Pressure, Heart_Rate, Daily_Steps):
    b,c = Blood_Pressure.split('/')
    systolic = int(b)
    diastolic = int(c)
    x = np.zeros(14)  
    print(x,b,c)

    input_values = np.array([[Sleep_Duration, Quality_of_Sleep, Physical_Activity_Level, 
                              Stress_Level, Heart_Rate, Daily_Steps, systolic, diastolic, Age]])

    a = scaler.transform(input_values)
    print(a)
    x[0] = a[0][8]
    x[1] = a[0][0]
    x[2] = a[0][1]
    x[3] = a[0][2]
    x[4] = a[0][3]
    x[5] = a[0][4]
    x[6] = a[0][5]
    if(Gender == "Male"):
        x[8] = 1
    else:
        x[7] = 1

    if (BMI_Category == 'Normal'):
        x[9] = 1
    elif (BMI_Category == 'Obese'):
        x[10] = 1
    else:
        x[11] = 1

    x[12] = a[0][6]
    x[13] = a[0][7]


    return rf.predict([x])

In [228]:
predict_disorder('Male',	27,	'Software Engineer',	6.1,	6,	42,	6,	'Overweight'	,'126/83',	77,	4200)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 126 83
[[   6.1    6.    42.     6.    77.  4200.   126.    83.    27. ]]

C:\Users\91962\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
C:\Users\91962\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([1], dtype=int64)